# Generated by Django 4.2.2 on 2023-06-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_auther_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(max_length=12, verbose_name="شماره موبایل")),
                ("subject", models.CharField(max_length=255, verbose_name="موضوع")),
                ("massage", models.TextField(verbose_name="پیام")),
            ],
        ),
    ]
