# Generated by Django 4.2.2 on 2023-07-03 06:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_massage_ticket_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("body", models.TextField(verbose_name="متن کامنت")),
                ("created", django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ("update", django_jalali.db.models.jDateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["created", "name"],
                        name="blog_commen_created_2df828_idx",
                    )
                ],
            },
        ),
    ]
