# Generated by Django 4.2.2 on 2023-07-07 08:25

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(default=0, verbose_name="زمان مطالعه"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False, verbose_name="وضعیت پذیرش"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="update",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ ویرایش"
            ),
        ),
    ]
