# Generated by Django 4.2.2 on 2023-07-09 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_ticket_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="send_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="تاریخ ارسال"
            ),
        ),
    ]
