# Generated by Django 4.2.3 on 2023-07-20 08:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='post_images/%Y/%m', verbose_name='عکس'),
        ),
    ]
