# Generated by Django 4.2.3 on 2023-07-23 05:43

import blog.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to=blog.models.upload_to, verbose_name='عکس'),
        ),
    ]
