# Generated by Django 4.2.3 on 2023-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='دسته بندی'),
        ),
    ]
